run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags:
  - 'all'

  # default: []
  skip-dirs:
  - 'internal/pb'

  # default: true
  skip-dirs-use-default: false

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

linters:
  enable:
  - 'asciicheck'
  - 'bodyclose'
  - 'depguard'
  - 'dogsled'
  - 'errcheck'
  - 'errorlint'
  - 'exportloopref'
  - 'gofmt'
  - 'gofumpt'
  - 'goheader'
  - 'goimports'
  - 'gomodguard'
  - 'goprintffuncname'
  - 'gosec'
  - 'gosimple'
  - 'govet'
  - 'ineffassign'
  - 'makezero'
  - 'misspell'
  - 'noctx'
  - 'paralleltest'
  - 'prealloc'
  - 'predeclared'
  - 'revive'
  - 'sqlclosecheck'
  - 'staticcheck'
  - 'stylecheck'
  - 'typecheck'
  - 'unconvert'
  - 'unused'
  - 'whitespace'

issues:
  # default: []
  exclude:
  - '^S1023:' # staticcheck: redundant returns help with http handlers
  - '^SA3000:' # staticcheck: not required in Go 11.4+
  - '^G102:' # gosec: we have to bind to all ifaces
  - '^G402:' # gosec: some services terminate at the load balancer
  - '^G505:' # gosec: we use crypto/sha1 for some HMACs
  - '^Range statement' # paralleltest: false positives
  - '^var-declaration:' # revive: false positive
  - '^exported:' # revive: backwards-compat

  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
