version: '3.9'

services:
  app-air:
    image: cosmtrek/air:v1.40.4
    working_dir: /goquizbox
    ports:
      - 8090:8090
    environment:
      - PORT=8090
      - DB_NAME=goquizbox
      - DB_USER=eutychus
      - DB_PASSWORD=eutychus
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PASSWORD=pass1234
      - REDIS_PORT=6379
      - LOG_LEVEL=debug
      - LOG_MODE=development
      - ENV=local
    volumes:
      - .:/goquizbox
      - ~/tmp/goair/goquizbox/pkg:/go/pkg
    networks:
      - goquizbox_net

volumes:
  goquizbox_app:

networks:
  goquizbox_net:
